name: Level Publish

on:
  workflow_dispatch:
    inputs:
      license_agreement:
        description: "I agree to the Level Submission License Agreement"
        required: true
        default: false
        type: boolean
      license_disclosures:
        description: "I have disclosed all third-party assets used in this level"
        required: true
        default: false
        type: boolean

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for checking and tagging

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.inputs.license_agreement == 'true' && github.event.inputs.license_disclosures == 'true'
    steps:
      - name: Setup env
        run: |
          if [ "${{ github.ref_name }}" = "${{ github.event.repository.default_branch }}" ]; then
            echo "ENV=prod" >> $GITHUB_ENV
          else
            echo "ENV=qa" >> $GITHUB_ENV
          fi

      - name: Get OIDC token
        id: get_token
        run: |
          TOKEN_JSON=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL")
          echo "JWT=$(echo $TOKEN_JSON | jq -r .value)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry==2.1.2

      - name: Install dependencies
        run: |
          poetry install -P .internal/deployer

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: .internal/package-lock.json

      - name: Install npm dependencies
        run: |
          npm ci --prefix .internal

      - name: Start Vite
        run: |
          cd .internal
          nohup npx vite --port 5173 > vite.log 2>&1 &
          sleep 10

      - name: Upload vite.log artifact
        uses: actions/upload-artifact@v4
        with:
          name: vite.log
          path: .internal/vite.log

      - name: Publish
        run: |
          echo "Publishing level..."
          poetry run -P .internal/deployer deployer \
            --jwt $JWT \
            --env $ENV \
            --level ./level
